package at.aau.serg.websocketbrokerdemo.network.dto

enum class GameMessageType {
    REQUEST_GAME_STATE,
    GAME_STATE,
    ROLL_DICE,
    ASK_BUY_PROPERTY,
    BUY_PROPERTY,
    ASK_PAY_PRISON,
    PAY_PRISON,
    ROLL_PRISON,
    ROLLED_PRISON,
    PAY_RENT,
    EXTRA_MESSAGE,

    PLAYER_MOVED,
    CAN_BUY_PROPERTY,
    PROPERTY_BOUGHT,
    CASH_TASK,
    GAME_OVER,
    MUST_PAY_RENT,
    ERROR,
    CURRENT_PLAYER,
    PLAYER_LOST,
    DRAW_RISK_CARD,
    DRAW_BANK_CARD,
    PAY_TAX,
    GO_TO_JAIL,
    PASS_START,
    BUILD_HOUSE,
    BUILD_HOTEL,
    DICE_ROLLED,
    PLAYER_OUT_OF_JAIL_CARD
}